[package]
name = "deposit_example"
edition = "2024.beta"
published-at = "0x0"

[dependencies.typus_dov]
git = "git@github.com:Typus-Lab/typus-interface.git"
subdir = "typus_dov_single"
rev = "mainnet"

[addresses]
deposit_example = "0x0"
