[package]
name = "typus_perp"
edition = "2024.beta"
version = "0.0.13"
published-at = "0xceddbccc7c674aba60f97104bbe218c59c84f6099d5692a35ec390c5c2dd1131"

[dependencies]
typus_oracle = { local = "../oracle" }
typus_dov = { local = "../typus_dov_single" }

[dependencies.MoveStdlib]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/move-stdlib"
rev = "mainnet"
override = true

[dependencies.Pyth]
git = "https://github.com/pyth-network/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "0918e2a405a99150f2079400738beba6fdb7769e"
override = true

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "mainnet"
override = true

[dependencies.SupraOracle]
git = "https://github.com/Entropy-Foundation/dora-interface.git"
subdir = "sui/mainnet/supra_holder"
rev = "5fec42547d9d446cc3fdc01754721d5a044462b6"
override = true

[dependencies.SwitchboardStdLib]
git = "git@github.com:Typus-Lab/sui-sdk.git"
subdir = "move/mainnet/switchboard_std"
rev = "main"
override = true

[dependencies.supra_utils]
git = "https://github.com/Entropy-Foundation/dora-interface.git"
subdir = "sui/mainnet/supra_utils"
rev = "5fec42547d9d446cc3fdc01754721d5a044462b6"
override = true

[dependencies.supra_validator]
git = "https://github.com/Entropy-Foundation/dora-interface.git"
subdir = "sui/mainnet/supra_validator"
rev = "5fec42547d9d446cc3fdc01754721d5a044462b6"
override = true

[addresses]
typus_perp = "0xe27969a70f93034de9ce16e6ad661b480324574e68d15a64b513fd90eb2423e5"
typus_perp_fee_address = "0x03e3f1ca852358b50837758b5197fedf61e2ea69186c469595baa717560963f9"
# upgrade_cap = "0x7855e4cf210eecbada3a273427ebf4f9b355b0cd052a5f51a9718a888f045427"
# Registry = "0xfee68e535bf24702be28fa38ea2d5946e617e0035027d5ca29dbed99efd82aaa"
# MarketRegistry = "0xc969d946a2b6b917a83b5fb71765793c4a52149e50d2c8cf5c01d7421fc7cd73"
# Version = "0xa12c282a068328833ec4a9109fc77803ec1f523f8da1bb0f82bac8450335f0c9"
# LpRegistry = "0xc0a8cc0201d202321cd40b3f19fcf4cc88d6b63ceac0de55b08a2ab16f8a721e"
# TreasuryCaps = "0x77c75fb1d78cca25b5e2d69decfe2837abf95c4ef44b809868e6ca20f42b63bc"
# TLP CoinMetadata = "0x655d36874ee37cf81bfca349e3cb13f64fbe8811c7e1134e32b8def114fea66c"
# 0xe27969a70f93034de9ce16e6ad661b480324574e68d15a64b513fd90eb2423e5::tlp::TLP
